'use client'
import { LegalLayout, LegalH2, LegalP, LegalList } from '../marketing-sections'

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Service"
      meta="Effective Date: July 1, 2025  ·  Operator: Carter King"
      navId="tokey" ftId="toftkey"
    >
      <LegalP>
        These Terms of Service (&#x201C;Terms&#x201D;) govern your access to and use of the Clavis application and website (the &#x201C;Service&#x201D;), operated by Carter King (&#x201C;we,&#x201D; &#x201C;us,&#x201D; or &#x201C;our&#x201D;). By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
      </LegalP>

      <LegalH2>1. Eligibility</LegalH2>
      <LegalP>You must be at least 18 years old and have the legal capacity to enter into a binding agreement to use the Service. By creating an account, you represent and warrant that you meet these requirements. The Service is intended for personal, non-commercial use by residents of the United States.</LegalP>

      <LegalH2>2. Account Registration</LegalH2>
      <LegalP>To access the full features of the Service, you must register with a valid email address. You are responsible for:</LegalP>
      <LegalList items={[
        'maintaining the confidentiality of your login credentials;',
        'all activity that occurs under your account; and',
        <>notifying us promptly at <a href="mailto:carterking18@gmail.com" style={{ color: 'var(--blue)' }}>carterking18@gmail.com</a> if you suspect unauthorized access to your account.</>,
      ]} />
      <LegalP>We reserve the right to suspend or terminate accounts that have been inactive for twelve (12) or more consecutive months, following reasonable advance notice to the email address on file.</LegalP>

      <LegalH2>3. Description of the Service</LegalH2>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>a. What Clavis provides</strong> — Clavis is a personal finance tracking tool. It allows you to manually log credit and debit card information and purchase history, estimates rewards based on the rates you enter, and suggests which card to use at a given merchant. The Service also offers optional weekly email summaries of card perks and credits.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>b. Reward estimates are not guarantees</strong> — All rewards calculations displayed in the Service are estimates based solely on information you manually enter. Actual rewards earned may differ due to card issuer terms, merchant category coding, promotional rate changes, and other factors outside our control. Clavis does not access your card issuer accounts and cannot verify your actual rewards balances. You should not rely on Clavis estimates for financial decisions without independently verifying with your card issuer.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>c. No financial advice</strong> — The Service does not provide financial, investment, tax, or legal advice of any kind. Card-use recommendations generated by the Service are based solely on the reward rates you enter and are provided for informational convenience only. Nothing in the Service constitutes a recommendation to open, close, or modify any financial account. Consult a qualified financial professional for personalized guidance.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>d. No bank connectivity</strong> — Clavis does not connect to any bank account, card issuer account, or financial institution. All data in the Service is entered manually by you. We are not a bank, payment processor, money transmitter, or financial institution of any kind.</LegalP>

      <LegalH2>4. Acceptable Use</LegalH2>
      <LegalP>You agree not to:</LegalP>
      <LegalList items={[
        'use the Service for any unlawful purpose or in violation of these Terms;',
        'attempt to gain unauthorized access to other users’ accounts or our systems;',
        'reverse engineer, decompile, or disassemble any portion of the Service;',
        'scrape, crawl, or automate access to the Service without our prior written consent;',
        'use the Service to store or transmit malicious code or harmful data;',
        'impersonate any person or entity or misrepresent your affiliation with any person or entity; or',
        'use the Service in any manner that could damage, disable, or impair its operation or interfere with other users’ access.',
      ]} />

      <LegalH2>5. Ownership of Your Data</LegalH2>
      <LegalP>You retain ownership of all information you enter into the Service. By entering data, you grant us a limited, non-exclusive, royalty-free license to store and process that data solely for the purpose of providing the Service to you. Our collection and use of your data is further governed by our <a href="/privacy" style={{ color: 'var(--blue)' }}>Privacy Policy</a>, incorporated into these Terms by reference.</LegalP>

      <LegalH2>6. Intellectual Property</LegalH2>
      <LegalP>All software, design, trademarks, and content comprising the Service, excluding user-entered data, are owned by or licensed to us. You may not copy, modify, distribute, or create derivative works from any element of the Service without our prior written consent.</LegalP>

      <LegalH2>7. Disclaimers</LegalH2>
      <LegalP style={{ textTransform: 'uppercase' }}>The Service is provided &#x201C;as is&#x201D; and &#x201C;as available&#x201D; without warranties of any kind, express or implied. To the fullest extent permitted by law, we disclaim all warranties, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be error-free, uninterrupted, secure, or free of defects.</LegalP>

      <LegalH2>8. Limitation of Liability</LegalH2>
      <LegalP style={{ textTransform: 'uppercase' }}>To the fullest extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including loss of data, loss of revenue, or financial losses resulting from reliance on reward estimates generated by the Service.</LegalP>
      <LegalP style={{ textTransform: 'uppercase' }}>Our total aggregate liability to you for any claim arising out of or related to these Terms or the Service shall not exceed the greater of (a) the total fees you paid to us in the twelve (12) months preceding the claim, or (b) fifty dollars ($50.00).</LegalP>

      <LegalH2>9. Indemnification</LegalH2>
      <LegalP>You agree to indemnify, defend, and hold harmless Clavis and its operator from any claims, losses, damages, liabilities, and expenses, including reasonable attorneys&#x2019; fees, arising out of your use of the Service, your violation of these Terms, or your violation of any third-party rights.</LegalP>

      <LegalH2>10. Termination</LegalH2>
      <LegalP>We may suspend or terminate your access to the Service at any time, with or without cause, with reasonable advance notice where practicable. You may delete your account at any time by contacting us at <a href="mailto:carterking18@gmail.com" style={{ color: 'var(--blue)' }}>carterking18@gmail.com</a>. Upon termination, your right to use the Service ceases immediately, and we will delete your personal data in accordance with our Privacy Policy.</LegalP>

      <LegalH2>11. Changes to These Terms</LegalH2>
      <LegalP>We reserve the right to modify these Terms at any time. We will notify registered users of material changes by email. Your continued use of the Service after the effective date of any updated Terms constitutes your acceptance of those changes. If you do not agree to updated Terms, you must stop using the Service and delete your account.</LegalP>

      <LegalH2>12. Governing Law</LegalH2>
      <LegalP>These Terms are governed by the laws of the State of New Hampshire, without regard to its conflict of law principles. Any dispute arising from these Terms or your use of the Service shall be resolved exclusively in the state or federal courts located in New Hampshire, and you consent to personal jurisdiction in those courts.</LegalP>

      <LegalH2>13. General Provisions</LegalH2>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>Entire Agreement.</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and us with respect to the Service and supersede all prior understandings.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>Severability.</strong> If any provision of these Terms is held unenforceable, the remaining provisions will continue in full force and effect.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>No Waiver.</strong> Our failure to enforce any right or provision of these Terms does not constitute a waiver of that right or provision.</LegalP>
      <LegalP><strong style={{ color: 'var(--text-primary)' }}>Assignment.</strong> You may not assign your rights or obligations under these Terms without our prior written consent. We may assign our rights without restriction.</LegalP>

      <LegalH2>14. Contact</LegalH2>
      <LegalP>Questions regarding these Terms may be directed to:</LegalP>
      <LegalP>
        Carter King<br/>
        New Hampshire, United States<br/>
        <a href="mailto:carterking18@gmail.com" style={{ color: 'var(--blue)' }}>carterking18@gmail.com</a>
      </LegalP>
    </LegalLayout>
  )
}
