const MERCHANTS = [
  // ── Dining ────────────────────────────────────────────────────────────
  { name: "Starbucks", category: "dining" },
  { name: "McDonald's", category: "dining" },
  { name: "Chick-fil-A", category: "dining" },
  { name: "Chipotle", category: "dining" },
  { name: "Subway", category: "dining" },
  { name: "Taco Bell", category: "dining" },
  { name: "Wendy's", category: "dining" },
  { name: "Burger King", category: "dining" },
  { name: "Domino's", category: "dining" },
  { name: "Pizza Hut", category: "dining" },
  { name: "Papa John's", category: "dining" },
  { name: "Panera Bread", category: "dining" },
  { name: "Dunkin", category: "dining" },
  { name: "Panda Express", category: "dining" },
  { name: "KFC", category: "dining" },
  { name: "Popeyes", category: "dining" },
  { name: "Five Guys", category: "dining" },
  { name: "Shake Shack", category: "dining" },
  { name: "Wingstop", category: "dining" },
  { name: "Buffalo Wild Wings", category: "dining" },
  { name: "Olive Garden", category: "dining" },
  { name: "Red Lobster", category: "dining" },
  { name: "Applebee's", category: "dining" },
  { name: "Chili's", category: "dining" },
  { name: "TGI Fridays", category: "dining" },
  { name: "Outback Steakhouse", category: "dining" },
  { name: "Texas Roadhouse", category: "dining" },
  { name: "Denny's", category: "dining" },
  { name: "IHOP", category: "dining" },
  { name: "Waffle House", category: "dining" },
  { name: "Cracker Barrel", category: "dining" },
  { name: "The Cheesecake Factory", category: "dining" },
  { name: "P.F. Chang's", category: "dining" },
  { name: "Raising Cane's", category: "dining" },
  { name: "Whataburger", category: "dining" },
  { name: "Sonic", category: "dining" },
  { name: "Dairy Queen", category: "dining" },
  { name: "Arby's", category: "dining" },
  { name: "Jack in the Box", category: "dining" },
  { name: "Carl's Jr", category: "dining" },
  { name: "Hardee's", category: "dining" },
  { name: "In-N-Out", category: "dining" },
  { name: "Wawa", category: "dining" },
  { name: "Dutch Bros", category: "dining" },
  { name: "Tim Hortons", category: "dining" },
  { name: "Culver's", category: "dining" },
  { name: "Jimmy John's", category: "dining" },
  { name: "Jersey Mike's", category: "dining" },
  { name: "Firehouse Subs", category: "dining" },
  { name: "Noodles & Company", category: "dining" },
  { name: "Zaxby's", category: "dining" },
  { name: "Cook Out", category: "dining" },
  { name: "Bojangles", category: "dining" },
  { name: "Freddy's", category: "dining" },

  // ── Grocery ───────────────────────────────────────────────────────────
  { name: "Whole Foods", category: "grocery" },
  { name: "Trader Joe's", category: "grocery" },
  { name: "Kroger", category: "grocery" },
  { name: "Safeway", category: "grocery" },
  { name: "Albertsons", category: "grocery" },
  { name: "Publix", category: "grocery" },
  { name: "HEB", category: "grocery" },
  { name: "H-E-B", category: "grocery" },
  { name: "Wegmans", category: "grocery" },
  { name: "Aldi", category: "grocery" },
  { name: "Lidl", category: "grocery" },
  { name: "Sprouts", category: "grocery" },
  { name: "Food Lion", category: "grocery" },
  { name: "Stop & Shop", category: "grocery" },
  { name: "Giant", category: "grocery" },
  { name: "Meijer", category: "grocery" },
  { name: "Winn-Dixie", category: "grocery" },
  { name: "Harris Teeter", category: "grocery" },
  { name: "Costco", category: "grocery" },
  { name: "Sam's Club", category: "grocery" },
  { name: "BJ's Wholesale", category: "grocery" },
  { name: "WinCo Foods", category: "grocery" },
  { name: "Smart & Final", category: "grocery" },
  { name: "Ralphs", category: "grocery" },
  { name: "Vons", category: "grocery" },
  { name: "Jewel-Osco", category: "grocery" },
  { name: "ShopRite", category: "grocery" },
  { name: "Market Basket", category: "grocery" },
  { name: "Hy-Vee", category: "grocery" },
  { name: "Brookshire's", category: "grocery" },

  // ── Gas ───────────────────────────────────────────────────────────────
  { name: "Shell", category: "gas" },
  { name: "Chevron", category: "gas" },
  { name: "Exxon", category: "gas" },
  { name: "Mobil", category: "gas" },
  { name: "BP", category: "gas" },
  { name: "Sunoco", category: "gas" },
  { name: "Marathon", category: "gas" },
  { name: "Speedway", category: "gas" },
  { name: "QuikTrip", category: "gas" },
  { name: "Casey's", category: "gas" },
  { name: "Circle K", category: "gas" },
  { name: "RaceTrac", category: "gas" },
  { name: "Pilot Flying J", category: "gas" },
  { name: "Love's", category: "gas" },
  { name: "Valero", category: "gas" },
  { name: "Murphy USA", category: "gas" },
  { name: "Kwik Trip", category: "gas" },
  { name: "Sheetz", category: "gas" },
  { name: "Cumberland Farms", category: "gas" },
  { name: "GetGo", category: "gas" },
  { name: "Holiday Stationstores", category: "gas" },
  { name: "Maverik", category: "gas" },

  // ── Travel ────────────────────────────────────────────────────────────
  { name: "Delta", category: "travel" },
  { name: "American Airlines", category: "travel" },
  { name: "United Airlines", category: "travel" },
  { name: "Southwest Airlines", category: "travel" },
  { name: "Spirit Airlines", category: "travel" },
  { name: "Frontier Airlines", category: "travel" },
  { name: "JetBlue", category: "travel" },
  { name: "Alaska Airlines", category: "travel" },
  { name: "Amtrak", category: "travel" },
  { name: "Uber", category: "travel" },
  { name: "Lyft", category: "travel" },
  { name: "Hertz", category: "travel" },
  { name: "Enterprise", category: "travel" },
  { name: "Avis", category: "travel" },
  { name: "Budget", category: "travel" },
  { name: "National Car Rental", category: "travel" },
  { name: "Dollar Rent A Car", category: "travel" },
  { name: "Thrifty", category: "travel" },
  { name: "Turo", category: "travel" },
  { name: "Greyhound", category: "travel" },
  { name: "Megabus", category: "travel" },
  { name: "FlixBus", category: "travel" },

  // ── Hotel ─────────────────────────────────────────────────────────────
  { name: "Marriott", category: "hotel" },
  { name: "Hilton", category: "hotel" },
  { name: "Hyatt", category: "hotel" },
  { name: "IHG", category: "hotel" },
  { name: "Wyndham", category: "hotel" },
  { name: "Best Western", category: "hotel" },
  { name: "Hampton Inn", category: "hotel" },
  { name: "Holiday Inn", category: "hotel" },
  { name: "Sheraton", category: "hotel" },
  { name: "Westin", category: "hotel" },
  { name: "W Hotels", category: "hotel" },
  { name: "Ritz-Carlton", category: "hotel" },
  { name: "Four Seasons", category: "hotel" },
  { name: "Airbnb", category: "hotel" },
  { name: "VRBO", category: "hotel" },
  { name: "Courtyard", category: "hotel" },
  { name: "Residence Inn", category: "hotel" },
  { name: "Fairfield Inn", category: "hotel" },
  { name: "DoubleTree", category: "hotel" },
  { name: "Embassy Suites", category: "hotel" },
  { name: "Homewood Suites", category: "hotel" },
  { name: "Extended Stay America", category: "hotel" },
  { name: "La Quinta", category: "hotel" },
  { name: "Motel 6", category: "hotel" },
  { name: "Days Inn", category: "hotel" },
  { name: "Super 8", category: "hotel" },
  { name: "Radisson", category: "hotel" },

  // ── Streaming ─────────────────────────────────────────────────────────
  { name: "Netflix", category: "streaming" },
  { name: "Hulu", category: "streaming" },
  { name: "Disney+", category: "streaming" },
  { name: "Max", category: "streaming" },
  { name: "HBO Max", category: "streaming" },
  { name: "Apple TV+", category: "streaming" },
  { name: "Peacock", category: "streaming" },
  { name: "Paramount+", category: "streaming" },
  { name: "ESPN+", category: "streaming" },
  { name: "YouTube Premium", category: "streaming" },
  { name: "Spotify", category: "streaming" },
  { name: "Apple Music", category: "streaming" },
  { name: "Tidal", category: "streaming" },
  { name: "Pandora", category: "streaming" },
  { name: "Amazon Prime", category: "streaming" },
  { name: "Fubo", category: "streaming" },
  { name: "Sling TV", category: "streaming" },
  { name: "YouTube TV", category: "streaming" },
  { name: "Philo", category: "streaming" },
  { name: "Crunchyroll", category: "streaming" },

  // ── Retail ────────────────────────────────────────────────────────────
  { name: "Amazon", category: "retail" },
  { name: "Target", category: "retail" },
  { name: "Walmart", category: "retail" },
  { name: "Best Buy", category: "retail" },
  { name: "Home Depot", category: "retail" },
  { name: "Lowe's", category: "retail" },
  { name: "IKEA", category: "retail" },
  { name: "Macy's", category: "retail" },
  { name: "Nordstrom", category: "retail" },
  { name: "TJ Maxx", category: "retail" },
  { name: "Marshalls", category: "retail" },
  { name: "HomeGoods", category: "retail" },
  { name: "Ross", category: "retail" },
  { name: "Burlington", category: "retail" },
  { name: "Gap", category: "retail" },
  { name: "Old Navy", category: "retail" },
  { name: "Banana Republic", category: "retail" },
  { name: "H&M", category: "retail" },
  { name: "Zara", category: "retail" },
  { name: "Uniqlo", category: "retail" },
  { name: "Nike", category: "retail" },
  { name: "Adidas", category: "retail" },
  { name: "Under Armour", category: "retail" },
  { name: "Foot Locker", category: "retail" },
  { name: "Dick's Sporting Goods", category: "retail" },
  { name: "REI", category: "retail" },
  { name: "PetSmart", category: "retail" },
  { name: "Petco", category: "retail" },
  { name: "CVS", category: "retail" },
  { name: "Walgreens", category: "retail" },
  { name: "Rite Aid", category: "retail" },
  { name: "Sephora", category: "retail" },
  { name: "Ulta", category: "retail" },
  { name: "Bath & Body Works", category: "retail" },
  { name: "Victoria's Secret", category: "retail" },
  { name: "GameStop", category: "retail" },
  { name: "Apple Store", category: "retail" },
  { name: "Microsoft Store", category: "retail" },
  { name: "Staples", category: "retail" },
  { name: "Office Depot", category: "retail" },
  { name: "AutoZone", category: "retail" },
  { name: "O'Reilly Auto Parts", category: "retail" },
  { name: "Advance Auto Parts", category: "retail" },
  { name: "Dollar General", category: "retail" },
  { name: "Dollar Tree", category: "retail" },
  { name: "Family Dollar", category: "retail" },
  { name: "Five Below", category: "retail" },
  { name: "Hobby Lobby", category: "retail" },
  { name: "Michaels", category: "retail" },
  { name: "Bed Bath & Beyond", category: "retail" },
  { name: "Williams-Sonoma", category: "retail" },
  { name: "Crate & Barrel", category: "retail" },
  { name: "Pottery Barn", category: "retail" },
  { name: "West Elm", category: "retail" },
  { name: "Wayfair", category: "retail" },
  { name: "Chewy", category: "retail" },
  { name: "eBay", category: "retail" },
  { name: "Etsy", category: "retail" },
  { name: "Kohl's", category: "retail" },
  { name: "JCPenney", category: "retail" },
  { name: "Sears", category: "retail" },
  { name: "Neiman Marcus", category: "retail" },
  { name: "Bloomingdale's", category: "retail" },
  { name: "Saks Fifth Avenue", category: "retail" },
  { name: "Louis Vuitton", category: "retail" },
  { name: "Gucci", category: "retail" },
  { name: "Lululemon", category: "retail" },
  { name: "Patagonia", category: "retail" },
  { name: "Columbia Sportswear", category: "retail" },
  { name: "Express", category: "retail" },
  { name: "American Eagle", category: "retail" },
  { name: "Abercrombie & Fitch", category: "retail" },
  { name: "Hollister", category: "retail" },
  { name: "Forever 21", category: "retail" },
  { name: "Shein", category: "retail" },
]

export function searchMerchants(query) {
  if (!query || query.length < 2) return []
  const lower = query.toLowerCase()
  return MERCHANTS
    .filter(m => m.name.toLowerCase().includes(lower))
    .slice(0, 6)
}

export function getMerchantCategory(name) {
  if (!name) return null
  const lower = name.toLowerCase()
  const match = MERCHANTS.find(m => m.name.toLowerCase() === lower)
  return match ? match.category : null
}
