const MERCHANTS = [
  // ── Dining ────────────────────────────────────────────────────────────
  // Fast food
  { name: "Starbucks", category: "dining" },
  { name: "McDonald's", category: "dining" },
  { name: "Chick-fil-A", category: "dining" },
  { name: "Chipotle", category: "dining" },
  { name: "Subway", category: "dining" },
  { name: "Taco Bell", category: "dining" },
  { name: "Wendy's", category: "dining" },
  { name: "Burger King", category: "dining" },
  { name: "Domino's", category: "dining" },
  { name: "Pizza Hut", category: "dining" },
  { name: "Papa John's", category: "dining" },
  { name: "Panera Bread", category: "dining" },
  { name: "Dunkin", category: "dining" },
  { name: "Panda Express", category: "dining" },
  { name: "KFC", category: "dining" },
  { name: "Popeyes", category: "dining" },
  { name: "Five Guys", category: "dining" },
  { name: "Shake Shack", category: "dining" },
  { name: "Wingstop", category: "dining" },
  { name: "Buffalo Wild Wings", category: "dining" },
  { name: "Arby's", category: "dining" },
  { name: "Jack in the Box", category: "dining" },
  { name: "Carl's Jr", category: "dining" },
  { name: "Hardee's", category: "dining" },
  { name: "In-N-Out", category: "dining" },
  { name: "Whataburger", category: "dining" },
  { name: "Sonic", category: "dining" },
  { name: "Dairy Queen", category: "dining" },
  { name: "Culver's", category: "dining" },
  { name: "Freddy's", category: "dining" },
  { name: "Wawa", category: "dining" },
  { name: "Cook Out", category: "dining" },
  { name: "Steak 'n Shake", category: "dining" },
  { name: "Checkers", category: "dining" },
  { name: "Rally's", category: "dining" },
  { name: "Del Taco", category: "dining" },
  { name: "Qdoba", category: "dining" },
  { name: "Moe's Southwest Grill", category: "dining" },
  { name: "Baja Fresh", category: "dining" },
  { name: "El Pollo Loco", category: "dining" },
  { name: "Habit Burger", category: "dining" },
  { name: "Smashburger", category: "dining" },
  { name: "Fatburger", category: "dining" },
  { name: "BurgerFi", category: "dining" },
  { name: "Portillo's", category: "dining" },

  // Coffee shops
  { name: "Dutch Bros", category: "dining" },
  { name: "Tim Hortons", category: "dining" },
  { name: "Peet's Coffee", category: "dining" },
  { name: "Caribou Coffee", category: "dining" },
  { name: "The Coffee Bean & Tea Leaf", category: "dining" },
  { name: "Biggby Coffee", category: "dining" },
  { name: "Scooter's Coffee", category: "dining" },
  { name: "7 Brew Coffee", category: "dining" },
  { name: "Philz Coffee", category: "dining" },
  { name: "Bluestone Lane", category: "dining" },

  // Sandwich & sub shops
  { name: "Jimmy John's", category: "dining" },
  { name: "Jersey Mike's", category: "dining" },
  { name: "Firehouse Subs", category: "dining" },
  { name: "Potbelly", category: "dining" },
  { name: "McAlister's Deli", category: "dining" },
  { name: "Schlotzsky's", category: "dining" },
  { name: "Jason's Deli", category: "dining" },
  { name: "Quiznos", category: "dining" },
  { name: "Which Wich", category: "dining" },
  { name: "Capriotti's", category: "dining" },

  // Chicken / wings
  { name: "Raising Cane's", category: "dining" },
  { name: "Zaxby's", category: "dining" },
  { name: "Bojangles", category: "dining" },
  { name: "Church's Chicken", category: "dining" },
  { name: "Slim Chickens", category: "dining" },
  { name: "PDQ", category: "dining" },
  { name: "Dave's Hot Chicken", category: "dining" },
  { name: "Chicken Salad Chick", category: "dining" },
  { name: "Roosters", category: "dining" },

  // Pizza
  { name: "Little Caesars", category: "dining" },
  { name: "Marco's Pizza", category: "dining" },
  { name: "Jet's Pizza", category: "dining" },
  { name: "Round Table Pizza", category: "dining" },
  { name: "Godfather's Pizza", category: "dining" },
  { name: "Cicis", category: "dining" },
  { name: "MOD Pizza", category: "dining" },
  { name: "Blaze Pizza", category: "dining" },
  { name: "California Pizza Kitchen", category: "dining" },

  // Mexican / Tex-Mex chains
  { name: "On The Border", category: "dining" },
  { name: "Chuy's", category: "dining" },
  { name: "Torchy's Tacos", category: "dining" },
  { name: "Tijuana Flats", category: "dining" },
  { name: "Fuzzy's Taco Shop", category: "dining" },
  { name: "Rosa's Café", category: "dining" },

  // Asian chains
  { name: "Pei Wei", category: "dining" },
  { name: "Yoshinoya", category: "dining" },
  { name: "Genghis Grill", category: "dining" },
  { name: "bd's Mongolian Grill", category: "dining" },
  { name: "Teriyaki Madness", category: "dining" },
  { name: "Sarku Japan", category: "dining" },
  { name: "Noodles & Company", category: "dining" },

  // Sit-down chains
  { name: "Olive Garden", category: "dining" },
  { name: "Red Lobster", category: "dining" },
  { name: "Applebee's", category: "dining" },
  { name: "Chili's", category: "dining" },
  { name: "TGI Fridays", category: "dining" },
  { name: "Outback Steakhouse", category: "dining" },
  { name: "Texas Roadhouse", category: "dining" },
  { name: "Denny's", category: "dining" },
  { name: "IHOP", category: "dining" },
  { name: "Waffle House", category: "dining" },
  { name: "Cracker Barrel", category: "dining" },
  { name: "The Cheesecake Factory", category: "dining" },
  { name: "P.F. Chang's", category: "dining" },
  { name: "LongHorn Steakhouse", category: "dining" },
  { name: "Carrabba's Italian Grill", category: "dining" },
  { name: "Bonefish Grill", category: "dining" },
  { name: "Bahama Breeze", category: "dining" },
  { name: "Yard House", category: "dining" },
  { name: "Bob Evans", category: "dining" },
  { name: "Big Boy", category: "dining" },
  { name: "Friendly's", category: "dining" },
  { name: "Perkins Restaurant", category: "dining" },
  { name: "Sizzler", category: "dining" },
  { name: "Golden Corral", category: "dining" },
  { name: "Ryan's", category: "dining" },
  { name: "Cheddar's Scratch Kitchen", category: "dining" },
  { name: "Red Robin", category: "dining" },
  { name: "Dine Brands", category: "dining" },
  { name: "BJ's Restaurant", category: "dining" },
  { name: "Dave & Buster's", category: "dining" },
  { name: "Seasons 52", category: "dining" },
  { name: "Eddie V's", category: "dining" },
  { name: "Morton's The Steakhouse", category: "dining" },
  { name: "Ruth's Chris Steak House", category: "dining" },
  { name: "Fleming's Prime Steakhouse", category: "dining" },

  // Bakeries
  { name: "Panera Bread", category: "dining" },
  { name: "Corner Bakery Cafe", category: "dining" },
  { name: "Great Harvest Bread", category: "dining" },
  { name: "Nothing Bundt Cakes", category: "dining" },
  { name: "Cinnabon", category: "dining" },
  { name: "Auntie Anne's", category: "dining" },
  { name: "Wetzel's Pretzels", category: "dining" },
  { name: "Einstein Bros Bagels", category: "dining" },
  { name: "Bruegger's Bagels", category: "dining" },
  { name: "Manhattan Bagel", category: "dining" },

  // Dessert / ice cream
  { name: "Baskin-Robbins", category: "dining" },
  { name: "Cold Stone Creamery", category: "dining" },
  { name: "Marble Slab Creamery", category: "dining" },
  { name: "Carvel", category: "dining" },
  { name: "Braum's", category: "dining" },
  { name: "Handel's Homemade Ice Cream", category: "dining" },
  { name: "Dippin' Dots", category: "dining" },
  { name: "Menchie's", category: "dining" },
  { name: "Yogurtland", category: "dining" },
  { name: "sweetFrog", category: "dining" },
  { name: "Orange Leaf", category: "dining" },
  { name: "Rita's Italian Ice", category: "dining" },
  { name: "Marble Slab", category: "dining" },
  { name: "Insomnia Cookies", category: "dining" },
  { name: "Great American Cookies", category: "dining" },
  { name: "Crumbl Cookies", category: "dining" },
  { name: "Krispy Kreme", category: "dining" },

  // Smoothies / juice bars
  { name: "Smoothie King", category: "dining" },
  { name: "Jamba", category: "dining" },
  { name: "Planet Smoothie", category: "dining" },
  { name: "Tropical Smoothie Cafe", category: "dining" },
  { name: "Robeks", category: "dining" },
  { name: "Squeezed", category: "dining" },
  { name: "Juice It Up!", category: "dining" },

  // Bars / pubs
  { name: "Buffalo Wild Wings", category: "dining" },
  { name: "Twin Peaks", category: "dining" },
  { name: "Hooters", category: "dining" },
  { name: "Yard House", category: "dining" },
  { name: "Miller's Ale House", category: "dining" },
  { name: "Bar Louie", category: "dining" },
  { name: "Brick House Tavern", category: "dining" },
  { name: "WineStyles Tasting Station", category: "dining" },

  // ── Grocery ───────────────────────────────────────────────────────────
  { name: "Whole Foods", category: "grocery" },
  { name: "Trader Joe's", category: "grocery" },
  { name: "Kroger", category: "grocery" },
  { name: "Safeway", category: "grocery" },
  { name: "Albertsons", category: "grocery" },
  { name: "Publix", category: "grocery" },
  { name: "HEB", category: "grocery" },
  { name: "H-E-B", category: "grocery" },
  { name: "Wegmans", category: "grocery" },
  { name: "Aldi", category: "grocery" },
  { name: "Lidl", category: "grocery" },
  { name: "Sprouts", category: "grocery" },
  { name: "Food Lion", category: "grocery" },
  { name: "Stop & Shop", category: "grocery" },
  { name: "Giant", category: "grocery" },
  { name: "Giant Food", category: "grocery" },
  { name: "Meijer", category: "grocery" },
  { name: "Winn-Dixie", category: "grocery" },
  { name: "Harris Teeter", category: "grocery" },
  { name: "Costco", category: "grocery" },
  { name: "Sam's Club", category: "grocery" },
  { name: "BJ's Wholesale", category: "grocery" },
  { name: "WinCo Foods", category: "grocery" },
  { name: "Smart & Final", category: "grocery" },
  { name: "Ralphs", category: "grocery" },
  { name: "Vons", category: "grocery" },
  { name: "Jewel-Osco", category: "grocery" },
  { name: "ShopRite", category: "grocery" },
  { name: "Market Basket", category: "grocery" },
  { name: "Hy-Vee", category: "grocery" },
  { name: "Brookshire's", category: "grocery" },
  { name: "Hannaford", category: "grocery" },
  { name: "Grocery Outlet", category: "grocery" },
  { name: "Price Chopper", category: "grocery" },
  { name: "The Fresh Market", category: "grocery" },
  { name: "Stater Bros", category: "grocery" },
  { name: "Ingles Markets", category: "grocery" },
  { name: "Weis Markets", category: "grocery" },
  { name: "Piggly Wiggly", category: "grocery" },
  { name: "Bi-Lo", category: "grocery" },
  { name: "Lucky Supermarkets", category: "grocery" },
  { name: "Raley's", category: "grocery" },
  { name: "Save Mart", category: "grocery" },
  { name: "Cub Foods", category: "grocery" },
  { name: "Fareway", category: "grocery" },
  { name: "Natural Grocers", category: "grocery" },
  { name: "Earth Fare", category: "grocery" },
  { name: "Fresh Thyme Market", category: "grocery" },
  { name: "Fry's Food", category: "grocery" },
  { name: "King Soopers", category: "grocery" },
  { name: "QFC", category: "grocery" },
  { name: "Fred Meyer", category: "grocery" },

  // ── Gas ───────────────────────────────────────────────────────────────
  { name: "Shell", category: "gas" },
  { name: "Chevron", category: "gas" },
  { name: "Exxon", category: "gas" },
  { name: "Mobil", category: "gas" },
  { name: "BP", category: "gas" },
  { name: "Sunoco", category: "gas" },
  { name: "Marathon", category: "gas" },
  { name: "Speedway", category: "gas" },
  { name: "QuikTrip", category: "gas" },
  { name: "Casey's", category: "gas" },
  { name: "Circle K", category: "gas" },
  { name: "RaceTrac", category: "gas" },
  { name: "Pilot Flying J", category: "gas" },
  { name: "Love's", category: "gas" },
  { name: "Valero", category: "gas" },
  { name: "Murphy USA", category: "gas" },
  { name: "Kwik Trip", category: "gas" },
  { name: "Sheetz", category: "gas" },
  { name: "Cumberland Farms", category: "gas" },
  { name: "GetGo", category: "gas" },
  { name: "Holiday Stationstores", category: "gas" },
  { name: "Maverik", category: "gas" },
  { name: "Citgo", category: "gas" },
  { name: "76", category: "gas" },
  { name: "Arco", category: "gas" },
  { name: "Getty", category: "gas" },
  { name: "Buc-ee's", category: "gas" },
  { name: "Pilot", category: "gas" },
  { name: "Flying J", category: "gas" },
  { name: "Thorntons", category: "gas" },
  { name: "Fuel Express", category: "gas" },
  { name: "Cenex", category: "gas" },
  { name: "Kum & Go", category: "gas" },
  { name: "Stewart's Shops", category: "gas" },

  // ── Travel ────────────────────────────────────────────────────────────
  // Airlines
  { name: "Delta", category: "travel" },
  { name: "American Airlines", category: "travel" },
  { name: "United Airlines", category: "travel" },
  { name: "Southwest Airlines", category: "travel" },
  { name: "Spirit Airlines", category: "travel" },
  { name: "Frontier Airlines", category: "travel" },
  { name: "JetBlue", category: "travel" },
  { name: "Alaska Airlines", category: "travel" },
  { name: "Allegiant Air", category: "travel" },
  { name: "Hawaiian Airlines", category: "travel" },
  { name: "Sun Country Airlines", category: "travel" },
  { name: "Breeze Airways", category: "travel" },
  { name: "Avelo Airlines", category: "travel" },

  // Ground / bus / rail
  { name: "Amtrak", category: "travel" },
  { name: "Greyhound", category: "travel" },
  { name: "Megabus", category: "travel" },
  { name: "FlixBus", category: "travel" },
  { name: "Trailways", category: "travel" },
  { name: "BoltBus", category: "travel" },

  // Rideshare
  { name: "Uber", category: "travel" },
  { name: "Lyft", category: "travel" },

  // Car rental
  { name: "Hertz", category: "travel" },
  { name: "Enterprise", category: "travel" },
  { name: "Avis", category: "travel" },
  { name: "Budget", category: "travel" },
  { name: "National Car Rental", category: "travel" },
  { name: "Alamo", category: "travel" },
  { name: "Dollar Rent A Car", category: "travel" },
  { name: "Thrifty", category: "travel" },
  { name: "Sixt", category: "travel" },
  { name: "Turo", category: "travel" },
  { name: "Zipcar", category: "travel" },

  // Booking & aggregators
  { name: "Expedia", category: "travel" },
  { name: "Booking.com", category: "travel" },
  { name: "Priceline", category: "travel" },
  { name: "Kayak", category: "travel" },
  { name: "Hotels.com", category: "travel" },
  { name: "Orbitz", category: "travel" },
  { name: "Travelocity", category: "travel" },
  { name: "Hotwire", category: "travel" },
  { name: "Trivago", category: "travel" },
  { name: "Google Flights", category: "travel" },
  { name: "CheapOair", category: "travel" },
  { name: "TripAdvisor", category: "travel" },

  // Parking
  { name: "SpotHero", category: "travel" },
  { name: "ParkWhiz", category: "travel" },
  { name: "LAZ Parking", category: "travel" },
  { name: "ParkMobile", category: "travel" },

  // Other travel
  { name: "AAA", category: "travel" },
  { name: "Global Entry", category: "travel" },
  { name: "TSA PreCheck", category: "travel" },
  { name: "CLEAR", category: "travel" },

  // ── Hotel ─────────────────────────────────────────────────────────────
  // Marriott family
  { name: "Marriott", category: "hotel" },
  { name: "Courtyard", category: "hotel" },
  { name: "Residence Inn", category: "hotel" },
  { name: "Fairfield Inn", category: "hotel" },
  { name: "Sheraton", category: "hotel" },
  { name: "Westin", category: "hotel" },
  { name: "W Hotels", category: "hotel" },
  { name: "Ritz-Carlton", category: "hotel" },
  { name: "St. Regis", category: "hotel" },
  { name: "Autograph Collection", category: "hotel" },
  { name: "Renaissance Hotels", category: "hotel" },
  { name: "Delta Hotels", category: "hotel" },
  { name: "Le Méridien", category: "hotel" },
  { name: "Tribute Portfolio", category: "hotel" },
  { name: "Design Hotels", category: "hotel" },

  // Hilton family
  { name: "Hilton", category: "hotel" },
  { name: "Hampton Inn", category: "hotel" },
  { name: "DoubleTree", category: "hotel" },
  { name: "Embassy Suites", category: "hotel" },
  { name: "Homewood Suites", category: "hotel" },
  { name: "Home2 Suites", category: "hotel" },
  { name: "Hilton Garden Inn", category: "hotel" },
  { name: "Conrad Hotels", category: "hotel" },
  { name: "Waldorf Astoria", category: "hotel" },
  { name: "Curio Collection", category: "hotel" },
  { name: "Tru by Hilton", category: "hotel" },

  // Hyatt family
  { name: "Hyatt", category: "hotel" },
  { name: "Grand Hyatt", category: "hotel" },
  { name: "Park Hyatt", category: "hotel" },
  { name: "Andaz", category: "hotel" },
  { name: "Hyatt Regency", category: "hotel" },
  { name: "Hyatt Place", category: "hotel" },
  { name: "Hyatt House", category: "hotel" },

  // IHG family
  { name: "IHG", category: "hotel" },
  { name: "Holiday Inn", category: "hotel" },
  { name: "Holiday Inn Express", category: "hotel" },
  { name: "InterContinental", category: "hotel" },
  { name: "Crowne Plaza", category: "hotel" },
  { name: "Kimpton", category: "hotel" },
  { name: "Regent Hotels", category: "hotel" },
  { name: "Even Hotels", category: "hotel" },
  { name: "Staybridge Suites", category: "hotel" },
  { name: "Candlewood Suites", category: "hotel" },

  // Wyndham / Choice / budget
  { name: "Wyndham", category: "hotel" },
  { name: "Best Western", category: "hotel" },
  { name: "Radisson", category: "hotel" },
  { name: "Extended Stay America", category: "hotel" },
  { name: "Motel 6", category: "hotel" },
  { name: "La Quinta", category: "hotel" },
  { name: "Days Inn", category: "hotel" },
  { name: "Super 8", category: "hotel" },
  { name: "Comfort Inn", category: "hotel" },
  { name: "Quality Inn", category: "hotel" },
  { name: "Sleep Inn", category: "hotel" },
  { name: "Clarion", category: "hotel" },
  { name: "Econo Lodge", category: "hotel" },
  { name: "Rodeway Inn", category: "hotel" },
  { name: "AmericInn", category: "hotel" },
  { name: "Microtel Inn & Suites", category: "hotel" },

  // Luxury / independent
  { name: "Four Seasons", category: "hotel" },
  { name: "Aman Resorts", category: "hotel" },
  { name: "Bellagio", category: "hotel" },
  { name: "MGM Grand", category: "hotel" },
  { name: "Caesars Palace", category: "hotel" },

  // Vacation rental
  { name: "Airbnb", category: "hotel" },
  { name: "VRBO", category: "hotel" },

  // ── Streaming ─────────────────────────────────────────────────────────
  // Video
  { name: "Netflix", category: "streaming" },
  { name: "Hulu", category: "streaming" },
  { name: "Disney+", category: "streaming" },
  { name: "Max", category: "streaming" },
  { name: "HBO Max", category: "streaming" },
  { name: "Apple TV+", category: "streaming" },
  { name: "Peacock", category: "streaming" },
  { name: "Paramount+", category: "streaming" },
  { name: "ESPN+", category: "streaming" },
  { name: "YouTube Premium", category: "streaming" },
  { name: "Amazon Prime Video", category: "streaming" },
  { name: "Amazon Prime", category: "streaming" },
  { name: "Crunchyroll", category: "streaming" },
  { name: "Fubo", category: "streaming" },
  { name: "FuboTV", category: "streaming" },
  { name: "Sling TV", category: "streaming" },
  { name: "YouTube TV", category: "streaming" },
  { name: "DirecTV Stream", category: "streaming" },
  { name: "Philo", category: "streaming" },
  { name: "Mubi", category: "streaming" },
  { name: "Shudder", category: "streaming" },
  { name: "Starz", category: "streaming" },
  { name: "Showtime", category: "streaming" },
  { name: "Cinemax", category: "streaming" },
  { name: "BritBox", category: "streaming" },
  { name: "Acorn TV", category: "streaming" },

  // Music / audio
  { name: "Spotify", category: "streaming" },
  { name: "Apple Music", category: "streaming" },
  { name: "Tidal", category: "streaming" },
  { name: "Pandora", category: "streaming" },
  { name: "SiriusXM", category: "streaming" },
  { name: "Audible", category: "streaming" },
  { name: "iHeartRadio", category: "streaming" },
  { name: "Deezer", category: "streaming" },
  { name: "Amazon Music", category: "streaming" },
  { name: "YouTube Music", category: "streaming" },

  // Gaming / live
  { name: "Twitch", category: "streaming" },
  { name: "Xbox Game Pass", category: "streaming" },
  { name: "PlayStation Plus", category: "streaming" },
  { name: "Nintendo Switch Online", category: "streaming" },
  { name: "EA Play", category: "streaming" },

  // ── Retail ────────────────────────────────────────────────────────────
  // Mass market / warehouse / dollar
  { name: "Amazon", category: "retail" },
  { name: "Target", category: "retail" },
  { name: "Walmart", category: "retail" },
  { name: "Costco", category: "retail" },
  { name: "Sam's Club", category: "retail" },
  { name: "BJ's Wholesale Club", category: "retail" },
  { name: "Dollar General", category: "retail" },
  { name: "Dollar Tree", category: "retail" },
  { name: "Family Dollar", category: "retail" },
  { name: "Five Below", category: "retail" },
  { name: "eBay", category: "retail" },
  { name: "Etsy", category: "retail" },

  // Department stores
  { name: "Macy's", category: "retail" },
  { name: "Nordstrom", category: "retail" },
  { name: "Bloomingdale's", category: "retail" },
  { name: "Saks Fifth Avenue", category: "retail" },
  { name: "Neiman Marcus", category: "retail" },
  { name: "Kohl's", category: "retail" },
  { name: "JCPenney", category: "retail" },
  { name: "Dillard's", category: "retail" },
  { name: "Belk", category: "retail" },
  { name: "Sears", category: "retail" },
  { name: "Nordstrom Rack", category: "retail" },
  { name: "Saks Off 5th", category: "retail" },

  // Off-price / home goods
  { name: "TJ Maxx", category: "retail" },
  { name: "Marshalls", category: "retail" },
  { name: "HomeGoods", category: "retail" },
  { name: "Ross", category: "retail" },
  { name: "Burlington", category: "retail" },
  { name: "Big Lots", category: "retail" },
  { name: "Tuesday Morning", category: "retail" },
  { name: "Ollie's Bargain Outlet", category: "retail" },

  // Clothing & apparel
  { name: "Gap", category: "retail" },
  { name: "Old Navy", category: "retail" },
  { name: "Banana Republic", category: "retail" },
  { name: "H&M", category: "retail" },
  { name: "Zara", category: "retail" },
  { name: "Uniqlo", category: "retail" },
  { name: "J.Crew", category: "retail" },
  { name: "J.Crew Factory", category: "retail" },
  { name: "Express", category: "retail" },
  { name: "Hollister", category: "retail" },
  { name: "Abercrombie & Fitch", category: "retail" },
  { name: "American Eagle", category: "retail" },
  { name: "Urban Outfitters", category: "retail" },
  { name: "Free People", category: "retail" },
  { name: "Anthropologie", category: "retail" },
  { name: "Forever 21", category: "retail" },
  { name: "Shein", category: "retail" },
  { name: "Aeropostale", category: "retail" },
  { name: "Cato", category: "retail" },
  { name: "New York & Company", category: "retail" },
  { name: "Chico's", category: "retail" },
  { name: "White House Black Market", category: "retail" },
  { name: "Ann Taylor", category: "retail" },
  { name: "LOFT", category: "retail" },
  { name: "Lane Bryant", category: "retail" },
  { name: "Torrid", category: "retail" },
  { name: "Talbots", category: "retail" },
  { name: "Brooks Brothers", category: "retail" },
  { name: "Vineyard Vines", category: "retail" },
  { name: "Bonobos", category: "retail" },
  { name: "Madewell", category: "retail" },
  { name: "Everlane", category: "retail" },
  { name: "Reformation", category: "retail" },
  { name: "Quay Australia", category: "retail" },
  { name: "Warby Parker", category: "retail" },
  { name: "LensCrafters", category: "retail" },

  // Activewear & sportswear
  { name: "Nike", category: "retail" },
  { name: "Adidas", category: "retail" },
  { name: "Under Armour", category: "retail" },
  { name: "Reebok", category: "retail" },
  { name: "New Balance", category: "retail" },
  { name: "Vans", category: "retail" },
  { name: "Converse", category: "retail" },
  { name: "Columbia Sportswear", category: "retail" },
  { name: "Patagonia", category: "retail" },
  { name: "The North Face", category: "retail" },
  { name: "Lululemon", category: "retail" },
  { name: "Athleta", category: "retail" },
  { name: "Fabletics", category: "retail" },
  { name: "Vuori", category: "retail" },
  { name: "Alo Yoga", category: "retail" },
  { name: "Arc'teryx", category: "retail" },
  { name: "Foot Locker", category: "retail" },
  { name: "Finish Line", category: "retail" },
  { name: "Shoe Carnival", category: "retail" },
  { name: "DSW", category: "retail" },
  { name: "Famous Footwear", category: "retail" },
  { name: "Skechers", category: "retail" },
  { name: "Steve Madden", category: "retail" },

  // Luxury
  { name: "Louis Vuitton", category: "retail" },
  { name: "Gucci", category: "retail" },
  { name: "Prada", category: "retail" },
  { name: "Burberry", category: "retail" },
  { name: "Coach", category: "retail" },
  { name: "Kate Spade", category: "retail" },
  { name: "Michael Kors", category: "retail" },
  { name: "Tory Burch", category: "retail" },
  { name: "Ralph Lauren", category: "retail" },
  { name: "Polo Ralph Lauren", category: "retail" },
  { name: "Hermès", category: "retail" },
  { name: "Tiffany & Co.", category: "retail" },
  { name: "Pandora Jewelry", category: "retail" },
  { name: "Kay Jewelers", category: "retail" },
  { name: "Zales", category: "retail" },
  { name: "Jared", category: "retail" },

  // Home furnishings & décor
  { name: "IKEA", category: "retail" },
  { name: "Pottery Barn", category: "retail" },
  { name: "West Elm", category: "retail" },
  { name: "Crate & Barrel", category: "retail" },
  { name: "Williams-Sonoma", category: "retail" },
  { name: "RH / Restoration Hardware", category: "retail" },
  { name: "Wayfair", category: "retail" },
  { name: "Article", category: "retail" },
  { name: "Havertys", category: "retail" },
  { name: "Ashley HomeStore", category: "retail" },
  { name: "Bob's Discount Furniture", category: "retail" },
  { name: "Rooms To Go", category: "retail" },
  { name: "Tuesday Morning", category: "retail" },
  { name: "Kirklands", category: "retail" },
  { name: "At Home", category: "retail" },
  { name: "Pier 1", category: "retail" },
  { name: "World Market", category: "retail" },

  // Electronics & tech
  { name: "Best Buy", category: "retail" },
  { name: "Apple Store", category: "retail" },
  { name: "Microsoft Store", category: "retail" },
  { name: "GameStop", category: "retail" },
  { name: "B&H Photo", category: "retail" },
  { name: "Micro Center", category: "retail" },
  { name: "Fry's Electronics", category: "retail" },
  { name: "Newegg", category: "retail" },

  // Books
  { name: "Barnes & Noble", category: "retail" },
  { name: "Books-A-Million", category: "retail" },

  // Pharmacy / health & beauty supply
  { name: "CVS", category: "retail" },
  { name: "Walgreens", category: "retail" },
  { name: "Rite Aid", category: "retail" },
  { name: "Duane Reade", category: "retail" },
  { name: "Sephora", category: "retail" },
  { name: "Ulta", category: "retail" },
  { name: "Sally Beauty", category: "retail" },
  { name: "Bath & Body Works", category: "retail" },
  { name: "Victoria's Secret", category: "retail" },
  { name: "PINK", category: "retail" },
  { name: "The Body Shop", category: "retail" },
  { name: "Lush", category: "retail" },
  { name: "Aveda", category: "retail" },
  { name: "Kiehl's", category: "retail" },
  { name: "Origins", category: "retail" },

  // Hardware / home improvement
  { name: "Home Depot", category: "retail" },
  { name: "Lowe's", category: "retail" },
  { name: "Menards", category: "retail" },
  { name: "Ace Hardware", category: "retail" },
  { name: "Harbor Freight", category: "retail" },
  { name: "True Value", category: "retail" },
  { name: "Do it Best", category: "retail" },

  // Craft / hobby / music
  { name: "Michaels", category: "retail" },
  { name: "Hobby Lobby", category: "retail" },
  { name: "Jo-Ann Fabrics", category: "retail" },
  { name: "Guitar Center", category: "retail" },
  { name: "Sweetwater", category: "retail" },
  { name: "JOANN", category: "retail" },
  { name: "Blick Art Materials", category: "retail" },
  { name: "AC Moore", category: "retail" },

  // Pet
  { name: "PetSmart", category: "retail" },
  { name: "Petco", category: "retail" },
  { name: "Pet Supplies Plus", category: "retail" },
  { name: "Chewy", category: "retail" },
  { name: "Hollywood Feed", category: "retail" },

  // Sporting goods / outdoors
  { name: "Dick's Sporting Goods", category: "retail" },
  { name: "REI", category: "retail" },
  { name: "Bass Pro Shops", category: "retail" },
  { name: "Cabela's", category: "retail" },
  { name: "Academy Sports", category: "retail" },
  { name: "Sportsman's Warehouse", category: "retail" },
  { name: "Big 5 Sporting Goods", category: "retail" },
  { name: "Field & Stream", category: "retail" },

  // Office supply
  { name: "Staples", category: "retail" },
  { name: "Office Depot", category: "retail" },
  { name: "OfficeMax", category: "retail" },

  // Auto parts
  { name: "AutoZone", category: "retail" },
  { name: "O'Reilly Auto Parts", category: "retail" },
  { name: "Advance Auto Parts", category: "retail" },
  { name: "Pep Boys", category: "retail" },
  { name: "NAPA Auto Parts", category: "retail" },
  { name: "Midas", category: "retail" },
  { name: "Jiffy Lube", category: "retail" },
  { name: "Firestone Complete Auto Care", category: "retail" },

  // Online / marketplace
  { name: "Overstock", category: "retail" },
  { name: "Rakuten", category: "retail" },
  { name: "AliExpress", category: "retail" },
  { name: "Poshmark", category: "retail" },
  { name: "ThredUp", category: "retail" },
  { name: "Depop", category: "retail" },
  { name: "Mercari", category: "retail" },
  { name: "StockX", category: "retail" },
  { name: "GOAT", category: "retail" },
  { name: "Vinted", category: "retail" },

  // Bed / bath / linen
  { name: "Bed Bath & Beyond", category: "retail" },
  { name: "Linens 'N Things", category: "retail" },
]

export function searchMerchants(query) {
  if (!query || query.length < 2) return []
  const lower = query.toLowerCase()
  return MERCHANTS
    .filter(m => m.name.toLowerCase().includes(lower))
    .slice(0, 6)
}

export function getMerchantCategory(name) {
  if (!name) return null
  const lower = name.toLowerCase()
  const match = MERCHANTS.find(m => m.name.toLowerCase() === lower)
  return match ? match.category : null
}
